Debug tag version extaction

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -25,7 +25,15 @@ jobs:
 
       - name: Extract tag version
         # expected tag format is vX.Y.Z
-        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
+        run: |
+          echo "Full GITHUB_REF: ${GITHUB_REF}"
+          TAG_VERSION=${GITHUB_REF#refs/tags/v}
+          if [ -z "$TAG_VERSION" ]; then
+            echo "Error: TAG_VERSION is empty. Exiting."
+            exit 1
+          fi
+          echo "Extracted TAG_VERSION: $TAG_VERSION"
+          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
 
       - name: Update package version
         run: npm version $TAG_VERSION --no-git-tag-version
